### ISSUE TITLE
RBDL에 관하여 궁금합니다

### ISSUE THREAD

**Issue by jeeseop** [psh117/dyros_jet#5]
먼저 새해복 많이 받으세요 개발자님
잘 지내고 계시죠?
궁금한 점이 있어 이렇게 이슈에 글을 남깁니다.

라이브러리에서 kinematic 과 dynamic solving을 위해 RBDL을 사용하셨는데요
혹시 KDL 과 RBDL 중에 RBDL을 택하신 이유나 장점 같은게 있는지 여쭈어도 될까요?

**Comment by psh117** [comment]
안녕하세요 jeeseop님,

**Comment by psh117** [comment]
안녕하세요 jeeseop님,
새해 복 많이 받으세요!

직접 모든 것을 비교해 보지는 않았지만 RBDL은 휴머노이드와 같이 Multi chain의 구성이 바로 해석되고 Kinematics, Dynamics가 계산되는 반면, KDL은 바로 해석이 안되는 것 같습니다. 

RBDL 개발자가 KDL에 남긴 글인데 참고하면 좋을 것 같습니다.
http://www.orocos.org/forum/orocos/orocos-users/kdl-and-dynamics-branched-models
